# =============================================================================
# 05-prometheus-pvc.yaml
# PersistentVolumeClaim para o Prometheus
# =============================================================================

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  labels:
    app: prometheus
    tier: monitoring
    project: controlservice
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
